[lint]
ignore = [
    "E731",  # Do not assign a `lambda` expression, use a `def`
    "F403",  # unable to detect undefined names
    "F405",  # may be undefined, or defined from star imports
    "E741",  # Ambiguous variable name: `l`
]
exclude = [
    "*.ipynb",
    "notebooks/",
]

[lint.per-file-ignores]
"__init__.py" = ["F401"]  # Ignore unused imports in __init__.py files

[format]
exclude = [
    "*.ipynb",
    "notebooks/",
]
